org: alimansour
app: onlinebe
service: online-be
frameworkVersion: "3"
provider:
  name: aws
  runtime: nodejs14.x
  environment:
    user_pool_id: { Ref: UserPool }
    client_id: { Ref: UserClient }
  iamRoleStatements:
    - Effect: Allow
      Action:
        - cognito-idp:AdminInitiateAuth
        - cognito-idp:AdminCreateUser
        - cognito-idp:AdminSetUserPassword
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:PostItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - s3:PutObject
        - s3:GetObject
        - s3:DeleteObject
        - s3:GetBucketLocation
        - s3:ListObjects
        - s3:ListBucketVersions
        - s3:ListBucketMultipartUploads
      Resource: "*"
functions:
  loginUser:
    handler: user/login.handler
    events:
      - http:
          path: user/login
          method: post
          cors: true

  signupUser:
    handler: user/signup.handler
    events:
      - http:
          path: user/signup
          method: post
          cors: true

  logoutUser:
    handler: user/logout.handler
    events:
      - http:
          path: logout
          method: get
          cors: true

  uploadPost:
    handler: post/upload.handler
    events:
      - http:
          path: post/upload
          method: post
          cors: true

  getPosts:
    handler: post/allposts.handler
    events:
      - http:
          path: posts
          method: post
          cors: true

  private:
    handler: auth/private.handler
    events:
      - http:
          path: private
          method: get
          cors: true
          authorizer:
            name: PrivateAuthorizer
            type: COGNITO_USER_POOLS
            arn:
              Fn::GetAtt:
                - UserPool
                - Arn
            claims:
              - email

#custom authorizer
  #         authorizer:
  #           name: Authorizer
  #           resultTtlInSeconds: 30
  #           identitySource: method.request.header.Authorization
  #           type: token
  # Authorizer:
  #   handler: auth/auth.handler
  #   description: ${self:service} authorizer
          #pre sign up trigger.. leaving here for future use | delete if not soon 12/9/22
  # autoConfirmUser:
  #   handler: user/autoconfirmuser.handler
  #   events:
  #     - cognitoUserPool:
  #         pool: serverless-auth-pool
  #         existing: true
  #         trigger: PreSignUp


  verifyUser:
    handler: user/verify.handler
    events:
      - http:
          path: user/verify
          method: post
          cors: true

  fetchNews:
    handler: post/cronfetchposts.handler
    events:
      - schedule: cron(0 * ? * * *)
      # Hourly: cron(0 * ? * * *)
      # Every two hours, starting at 12 AM UTC: cron(0 0/2 ? * * *)
      # https://docs.aws.amazon.com/sagemaker/latest/dg/model-monitor-schedule-expression.html

resources:
  Resources:
    UserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: serverless-auth-pool
        Schema:
          - Name: email
            Required: true
            Mutable: true
        Policies:
          PasswordPolicy:
            MinimumLength: 6
        AutoVerifiedAttributes: ["email"]

    UserClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: user-pool-ui
        GenerateSecret: false
        UserPoolId: { Ref: UserPool }
        AccessTokenValidity: 5
        IdTokenValidity: 5
        ExplicitAuthFlows:
          - "ALLOW_ADMIN_USER_PASSWORD_AUTH"
          - "ALLOW_REFRESH_TOKEN_AUTH"

    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usersTable1
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: username
            KeyType: HASH
          - AttributeName: email
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    postsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: postsTable1
        AttributeDefinitions:
          - AttributeName: type
            AttributeType: S
          - AttributeName: url
            AttributeType: S
          - AttributeName: uploadDate
            AttributeType: N
          - AttributeName: recommended
            AttributeType: N
          - AttributeName: upVotes
            AttributeType: N
        KeySchema:
          - AttributeName: type
            KeyType: HASH
          - AttributeName: url
            KeyType: RANGE
        LocalSecondaryIndexes:
          - IndexName: uploadDateLSI
            KeySchema:
              - AttributeName: type
                KeyType: HASH
              - AttributeName: uploadDate
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: upVoteLSI
            KeySchema:
              - AttributeName: type
                KeyType: HASH
              - AttributeName: upVotes
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: recommendedLSI
            KeySchema:
              - AttributeName: type
                KeyType: HASH
              - AttributeName: recommended
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    ImageBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: imagebucket-alimansour

    postImageBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref ImageBucket
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Action:
                - "s3:GetObject"
              Effect: Allow
              Principal: "*"
              Resource: "arn:aws:s3:::imagebucket-alimansour/*"
